// Generated by `php artisan actions:typescript` from agentic-actions/laravel 0.9.0-beta.3. Do not edit.
import { action, uri, type ActionDefinition } from '@agentic-actions/client';

export type CompletedPerDayParams = { current_team: string | number };

export type CompletedPerDayInput = {
    /** How many days back, today included. 14 when left out. */
    days?: number;
};

export type CompletedPerDayOutput = {
    columns: Array<{
        key: 'day' | 'completed';
        label: string;
        type: 'text' | 'integer' | 'number' | 'money' | 'percent' | 'date' | 'datetime' | 'boolean';
        currency?: string;
        decimals?: number;
        description?: string;
    }>;
    rows: Array<{
        day?: string | null;
        completed?: number | null;
    }>;
    truncated: boolean;
    chart: {
        type: 'line' | 'bar' | 'metric' | 'none';
        x?: 'day' | 'completed';
        y: Array<'day' | 'completed'>;
    };
    caption: string | null;
};

/** Show the person a table and line chart of how many of the current team's tasks were completed each day, over the last few days. Use it for the team's pace, velocity, or "how much did we finish this week". */
export const completedPerDay = (params: CompletedPerDayParams): ActionDefinition<CompletedPerDayInput, CompletedPerDayOutput> =>
    action({ name: 'completed-per-day', method: 'post', url: uri('/{current_team}/actions/completed-per-day', params), touches: [] });

export type CompletionStatsParams = { current_team: string | number };

export type CompletionStatsInput = {
    /** What to compute, one to five of: tasks: Completed tasks. */
    measures: Array<'tasks'>;
    /** Group the rows by one or two of: priority: Priority; assignee: Assignee; project: Project. */
    by?: Array<'priority' | 'assignee' | 'project'> | null;
    /** One row per day, week (from Monday), month, quarter or year of completed: Completed, every one in the range; never with by. */
    grain?: 'day' | 'week' | 'month' | 'quarter' | 'year' | null;
    /** The first day: -30d, -8w, -6m, -2q or -1y counts back to the start of that day, week, month, quarter or year, or a date as YYYY-MM-DD; by default -12m. */
    since?: string | null;
    /** The last day, included: today (the default) or a date as YYYY-MM-DD. */
    until?: string | null;
    /** Keep the rows whose dimension is one of the values, or with exclude, none of them (rows with no value stay). */
    filters?: Array<{
        dimension: 'priority' | 'assignee' | 'project';
        values: Array<string>;
        exclude?: boolean | null;
    }> | null;
    /** Add each measure in the previous period of the same length, and its change. */
    compare?: boolean | null;
    /** Sort by a chosen measure or dimension, or by the time with grain; by default the time with grain, else the first measure. */
    sort?: 'completed' | 'priority' | 'assignee' | 'project' | 'tasks' | null;
    /** Sort from the lowest; by default dimensions sort from the lowest and measures from the highest. */
    ascending?: boolean | null;
    /** The most rows, 1 to 500; by default 50; with grain every bucket comes back. */
    limit?: number | null;
};

export type CompletionStatsOutput = {
    columns: Array<{
        key: 'completed' | 'priority' | 'assignee' | 'project' | 'tasks' | 'tasks_previous' | 'tasks_change';
        label: string;
        type: 'text' | 'integer' | 'number' | 'money' | 'percent' | 'date' | 'datetime' | 'boolean';
        currency?: string;
        decimals?: number;
        description?: string;
    }>;
    rows: Array<{
        completed?: string | null;
        priority?: string | null;
        assignee?: string | null;
        project?: string | null;
        tasks?: number | null;
        tasks_previous?: number | null;
        tasks_change?: number | null;
    }>;
    truncated: boolean;
    chart: {
        type: 'line' | 'bar' | 'metric' | 'none';
        x?: 'completed' | 'priority' | 'assignee' | 'project' | 'tasks' | 'tasks_previous' | 'tasks_change';
        y: Array<'completed' | 'priority' | 'assignee' | 'project' | 'tasks' | 'tasks_previous' | 'tasks_change'>;
    };
    caption: string | null;
};

/** Answer a question about the tasks the current team completed, with a table and chart: count them by when they were completed, priority, assignee or project, filter them, and compare with the previous period. Use it for questions such as tasks completed per week or who completed the most this month. */
export const completionStats = (params: CompletionStatsParams): ActionDefinition<CompletionStatsInput, CompletionStatsOutput> =>
    action({ name: 'completion-stats', method: 'post', url: uri('/{current_team}/actions/completion-stats', params), touches: [] });

export type CreateProjectParams = { current_team: string | number };

export type CreateProjectInput = {
    /** A short name, unique within the team. */
    name: string;
    /** What the project is for. Optional. */
    description?: string | null;
};

export type CreateProjectOutput = {
    id: number;
    name: string;
};

/** Create a project in the current team. Tasks can then be filed under it by name. */
export const createProject = (params: CreateProjectParams): ActionDefinition<CreateProjectInput, CreateProjectOutput> =>
    action({ name: 'create-project', method: 'post', url: uri('/{current_team}/actions/create-project', params), touches: ['projects'] });

export type CreateTaskParams = { current_team: string | number };

export type CreateTaskInput = {
    /** A short title, such as "Draft the launch post". */
    title: string;
    /** Longer details. Optional. */
    description?: string | null;
    /** The board column: todo, doing or done. A new task starts in todo. */
    status?: 'todo' | 'doing' | 'done' | null;
    /** How urgent it is: low, normal or high. */
    priority?: 'low' | 'normal' | 'high' | null;
    /** The day it should be done by. */
    due_on?: string | null;
    /** Who does it: a member of this team, by email or full name. */
    assignee?: string | null;
    /** The name of one of this team's projects, or null for none. */
    project?: string | null;
};

export type CreateTaskOutput = {
    task: {
        id: number;
        title: string;
        description: string | null;
        status: 'todo' | 'doing' | 'done';
        priority: 'low' | 'normal' | 'high';
        due_on: string | null;
        overdue: boolean;
        assignee: {
            name: string;
            email: string;
        } | null;
        project: string | null;
    };
};

/** Create a task on the current team's board. Name the assignee by email or full name and the project by its name. */
export const createTask = (params: CreateTaskParams): ActionDefinition<CreateTaskInput, CreateTaskOutput> =>
    action({ name: 'create-task', method: 'post', url: uri('/{current_team}/actions/create-task', params), touches: ['tasks', 'summary'] });

export type DeleteTaskParams = { current_team: string | number };

export type DeleteTaskInput = {
    /** The task number, as list-tasks and search-tasks return it in "id". */
    task: number;
};

export type DeleteTaskOutput = Record<string, never>;

/** Delete a task from the current team's board for good. Get the task number from list-tasks or search-tasks. */
export const deleteTask = (params: DeleteTaskParams): ActionDefinition<DeleteTaskInput, DeleteTaskOutput> =>
    action({ name: 'delete-task', method: 'post', url: uri('/{current_team}/actions/delete-task', params), touches: ['tasks', 'summary'] });

export type ListTasksParams = { current_team: string | number };

export type ListTasksInput = {
    /** Only tasks in this column: todo, doing or done. */
    status?: 'todo' | 'doing' | 'done' | null;
    /** Only tasks of this priority. */
    priority?: 'low' | 'normal' | 'high' | null;
    /** Only tasks assigned to this member, by email or full name. "me" means the person asking. */
    assignee?: string | null;
    /** Only tasks of this project, by name. */
    project?: string | null;
    /** true for only the tasks past their due date and not done. */
    overdue?: boolean;
};

export type ListTasksOutput = {
    tasks: Array<{
        id: number;
        title: string;
        description: string | null;
        status: 'todo' | 'doing' | 'done';
        priority: 'low' | 'normal' | 'high';
        due_on: string | null;
        overdue: boolean;
        assignee: {
            name: string;
            email: string;
        } | null;
        project: string | null;
    }>;
};

/** List the current team's tasks, highest priority and soonest due first. Every filter is optional. */
export const listTasks = (params: ListTasksParams): ActionDefinition<ListTasksInput, ListTasksOutput> =>
    action({ name: 'list-tasks', method: 'post', url: uri('/{current_team}/actions/list-tasks', params), touches: [] });

export type SearchTasksParams = { current_team: string | number };

export type SearchTasksInput = {
    /** Words from the task's title or details. */
    query: string;
};

export type SearchTasksOutput = {
    tasks: Array<{
        id: number;
        title: string;
        description: string | null;
        status: 'todo' | 'doing' | 'done';
        priority: 'low' | 'normal' | 'high';
        due_on: string | null;
        overdue: boolean;
        assignee: {
            name: string;
            email: string;
        } | null;
        project: string | null;
    }>;
};

/** Search the current team's tasks by words in their title or details. Returns up to 20 matches with their task numbers. */
export const searchTasks = (params: SearchTasksParams): ActionDefinition<SearchTasksInput, SearchTasksOutput> =>
    action({ name: 'search-tasks', method: 'post', url: uri('/{current_team}/actions/search-tasks', params), touches: [] });

export type SummarizeBoardParams = { current_team: string | number };

export type SummarizeBoardInput = Record<string, never>;

export type SummarizeBoardOutput = {
    total: number;
    todo: number;
    doing: number;
    done: number;
    /** Past their due date and not done. */
    overdue: number;
    /** Not done, due today or within the next seven days. */
    due_soon: number;
    /** Not done and assigned to nobody. */
    unassigned: number;
};

/** Count the current team's tasks by status, and how many are overdue, due within the next seven days, or unassigned. */
export const summarizeBoard = (params: SummarizeBoardParams): ActionDefinition<SummarizeBoardInput, SummarizeBoardOutput> =>
    action({ name: 'summarize-board', method: 'post', url: uri('/{current_team}/actions/summarize-board', params), touches: [] });

export type TaskStatsParams = { current_team: string | number };

export type TaskStatsInput = {
    /** What to compute, one to five of: tasks: Tasks; done: Done; done_share: Done share. */
    measures: Array<'tasks' | 'done' | 'done_share'>;
    /** Group the rows by one or two of: status: Column; priority: Priority; assignee: Assignee; project: Project. */
    by?: Array<'status' | 'priority' | 'assignee' | 'project'> | null;
    /** One row per day, week (from Monday), month, quarter or year of added: Added, every one in the range; never with by. */
    grain?: 'day' | 'week' | 'month' | 'quarter' | 'year' | null;
    /** The first day: -30d, -8w, -6m, -2q or -1y counts back to the start of that day, week, month, quarter or year, or a date as YYYY-MM-DD; by default -12m. */
    since?: string | null;
    /** The last day, included: today (the default) or a date as YYYY-MM-DD. */
    until?: string | null;
    /** Keep the rows whose dimension is one of the values, or with exclude, none of them (rows with no value stay). */
    filters?: Array<{
        dimension: 'status' | 'priority' | 'assignee' | 'project';
        values: Array<string>;
        exclude?: boolean | null;
    }> | null;
    /** Add each measure in the previous period of the same length, and its change. */
    compare?: boolean | null;
    /** Sort by a chosen measure or dimension, or by the time with grain; by default the time with grain, else the first measure. */
    sort?: 'added' | 'status' | 'priority' | 'assignee' | 'project' | 'tasks' | 'done' | 'done_share' | null;
    /** Sort from the lowest; by default dimensions sort from the lowest and measures from the highest. */
    ascending?: boolean | null;
    /** The most rows, 1 to 500; by default 50; with grain every bucket comes back. */
    limit?: number | null;
};

export type TaskStatsOutput = {
    columns: Array<{
        key: 'added' | 'status' | 'priority' | 'assignee' | 'project' | 'tasks' | 'done' | 'done_share' | 'tasks_previous' | 'tasks_change' | 'done_previous' | 'done_change';
        label: string;
        type: 'text' | 'integer' | 'number' | 'money' | 'percent' | 'date' | 'datetime' | 'boolean';
        currency?: string;
        decimals?: number;
        description?: string;
    }>;
    rows: Array<{
        added?: string | null;
        status?: string | null;
        priority?: string | null;
        assignee?: string | null;
        project?: string | null;
        tasks?: number | null;
        done?: number | null;
        done_share?: number | null;
        tasks_previous?: number | null;
        tasks_change?: number | null;
        done_previous?: number | null;
        done_change?: number | null;
    }>;
    truncated: boolean;
    chart: {
        type: 'line' | 'bar' | 'metric' | 'none';
        x?: 'added' | 'status' | 'priority' | 'assignee' | 'project' | 'tasks' | 'done' | 'done_share' | 'tasks_previous' | 'tasks_change' | 'done_previous' | 'done_change';
        y: Array<'added' | 'status' | 'priority' | 'assignee' | 'project' | 'tasks' | 'done' | 'done_share' | 'tasks_previous' | 'tasks_change' | 'done_previous' | 'done_change'>;
    };
    caption: string | null;
};

/** Answer a question about the current team's tasks with a table and chart: count them by when they were added, status, priority, assignee or project, filter them, and compare with the previous period. Use it when no other report fits, such as high-priority tasks per person or tasks added per week. */
export const taskStats = (params: TaskStatsParams): ActionDefinition<TaskStatsInput, TaskStatsOutput> =>
    action({ name: 'task-stats', method: 'post', url: uri('/{current_team}/actions/task-stats', params), touches: [] });

export type TasksByAssigneeParams = { current_team: string | number };

export type TasksByAssigneeInput = Record<string, never>;

export type TasksByAssigneeOutput = {
    columns: Array<{
        key: 'assignee' | 'open' | 'done' | 'done_share';
        label: string;
        type: 'text' | 'integer' | 'number' | 'money' | 'percent' | 'date' | 'datetime' | 'boolean';
        currency?: string;
        decimals?: number;
        description?: string;
    }>;
    rows: Array<{
        assignee?: string | null;
        open?: number | null;
        done?: number | null;
        /** Done tasks out of all their tasks. */
        done_share?: number | null;
    }>;
    truncated: boolean;
    chart: {
        type: 'line' | 'bar' | 'metric' | 'none';
        x?: 'assignee' | 'open' | 'done' | 'done_share';
        y: Array<'assignee' | 'open' | 'done' | 'done_share'>;
    };
    caption: string | null;
};

/** Show the person a table and chart of the current team's tasks per assignee: open, done, and the share done, busiest first. Use it for "who has the most tasks", workload, or "how is each person doing". */
export const tasksByAssignee = (params: TasksByAssigneeParams): ActionDefinition<TasksByAssigneeInput, TasksByAssigneeOutput> =>
    action({ name: 'tasks-by-assignee', method: 'post', url: uri('/{current_team}/actions/tasks-by-assignee', params), touches: [] });

export type TasksByStatusParams = { current_team: string | number };

export type TasksByStatusInput = Record<string, never>;

export type TasksByStatusOutput = {
    columns: Array<{
        key: 'status' | 'tasks' | 'overdue';
        label: string;
        type: 'text' | 'integer' | 'number' | 'money' | 'percent' | 'date' | 'datetime' | 'boolean';
        currency?: string;
        decimals?: number;
        description?: string;
    }>;
    rows: Array<{
        status?: string | null;
        tasks?: number | null;
        /** Past their due date and not done. */
        overdue?: number | null;
    }>;
    truncated: boolean;
    chart: {
        type: 'line' | 'bar' | 'metric' | 'none';
        x?: 'status' | 'tasks' | 'overdue';
        y: Array<'status' | 'tasks' | 'overdue'>;
    };
    caption: string | null;
};

/** Show the person a table and chart of the current team's tasks per board column (To do, Doing, Done), with how many of each are overdue. Use it for "how many tasks are in each column" or a chart of the board. */
export const tasksByStatus = (params: TasksByStatusParams): ActionDefinition<TasksByStatusInput, TasksByStatusOutput> =>
    action({ name: 'tasks-by-status', method: 'post', url: uri('/{current_team}/actions/tasks-by-status', params), touches: [] });

export type UpdateTaskParams = { current_team: string | number };

export type UpdateTaskInput = {
    /** The task number, as list-tasks and search-tasks return it in "id". */
    task: number;
    /** A short title, such as "Draft the launch post". */
    title?: string;
    /** Longer details. Optional. */
    description?: string | null;
    /** The board column: todo, doing or done. A new task starts in todo. */
    status?: 'todo' | 'doing' | 'done' | null;
    /** low, normal or high. A new task is normal. */
    priority?: 'low' | 'normal' | 'high' | null;
    /** The due date as YYYY-MM-DD, or null for none. */
    due_on?: string | null;
    /** The email or full name of a member of this team, or null for nobody. */
    assignee?: string | null;
    /** The name of one of this team's projects, or null for none. */
    project?: string | null;
};

export type UpdateTaskOutput = {
    task: {
        id: number;
        title: string;
        description: string | null;
        status: 'todo' | 'doing' | 'done';
        priority: 'low' | 'normal' | 'high';
        due_on: string | null;
        overdue: boolean;
        assignee: {
            name: string;
            email: string;
        } | null;
        project: string | null;
    };
};

/** Change a task on the current team's board: move it to another status, reassign it, or edit its title, details, priority, due date or project. Send only the fields to change. Get the task number from list-tasks or search-tasks. */
export const updateTask = (params: UpdateTaskParams): ActionDefinition<UpdateTaskInput, UpdateTaskOutput> =>
    action({ name: 'update-task', method: 'post', url: uri('/{current_team}/actions/update-task', params), touches: ['tasks', 'summary'] });
